travis:
  secure:
    BINSTAR_TOKEN: PMhK+45kv/RPC1NfKvMDBpbuJIovJ5Y3YDsI8qz0w8Yb/cR5yJf2QVVUL/5LmWBwhYHcAkNI2nRwQzC21C30ENsecLlpOgMIcd8CNAE0FxkBgsN0AckHCiYPGSufOO5i8G1FJqWIBKSjTu0TWEFBICQyL9hSQXmd1x4tFkTYynGbE5dgu1pKuknMjFFJipm9FQSiWqwEDOFpJrYg7YQQNwReBKU4a9PqJC5+EOYcqaQQHbnAqgXZj7MKsTsZV7vM3z3kpFsFa0/YNPq6/W0WKUtX2l8+0JuaYOEg7HYs8o1kcSReyn657t/TQcFGNp2F97AC8A9RCoMYUVXD1wjIVEFeuvrlbGsk4IMOt9wVSL7TilL/iQhwIxNmNGQA9Pea1L6yHIqdk+44BSnO58uA907s4EfhbLvu4LdA90pJ3rXO/vKEN15T0T1Qzl4TaoNtCov2Ou4241DCKLDMx7B1Bqds8u4C+F4pxqh29vOacFz6tXz+lJjF4OVBMfHU9ShbF7f5H0CPZl4xprIwUv1WKfIi+kkEkWp2ioQ4i/cAquPpK6BKxuk8CmnFp4OtfWNu9iR1dXxEysy4JHNCFhBNSuUAcb4uRsNb7YgfllCYpl/DAEBpqYWk3kkkTWTJw+LZFsfikfShaUhnXewV+mGQrAArOd4OEAspU3yrwpZBVdI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
