travis:
  secure:
    BINSTAR_TOKEN: ajtxPn9hRzm+OEaRzFMFxwvX6Rt7/Ph6nne7QK+bHSwCK6JJtmxvDB01sEyFgUwrVP1vbb+PGSOG3EOILgtue2xulg4Xm2gnNBNIpoEAJeGOIOSXUZLcsAz/mhvIvIU1iFgJqegDsC6kn5xRtKD7mMiVCPH2SQUQePUJ+JVTLBgGbDGiQyK1jN6k/3okXO0OsDeKSDmnIGd9gWlOK7PaJPUkQ8Vf6xVKCUupvAbngsKv1klTbSKxamk9/y6MklC8LjU/6R6knHbw161fqvXBjDNxBWAg7+1BSWAVJGbm/Bx5dE3O0CYyZ8KsdkB0UO3NUGnOucY12kb1ODxhSkwo1rsfhw5KJbOUzVxS2lzP6JXrJkbBcTsRoQLHHqrXnWNIVrIqEWbvC4Vuu8TfxxniDJ97aeRTA7BBfEghba8lwqZF9ZyCBI+M5wj2v6zaTJ/4e6PhCPuqSp4Q5TwGrGQKCUk0Shl/gulfi9pC9mcIup7Pi4jNxot4GMcNeRbsJSC1eS/Zrrr2tWUYbnquGD/mkYl7aouJT6vVm23Lw+35kE5dp7Qn8lzaz84hzEja+dPGxoNILPDQpv5uHoRz4sK9Cj9TXRoBrI1hmV0REuWB/LXmb9b/wJoZzZw8HSE3VKJp0pG7j1/h/yUaUHScavtBECMzWfTT/EoNYYC5h/Gmt3Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
